import type { Metadata } from "next";

import Providers from "./providers";

import "../styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased w-full h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
